# Gmail 설정
GMAIL_CLIENT_ID=your-client-id.apps.googleusercontent.com
GMAIL_CLIENT_SECRET=your-client-secret
GMAIL_REFRESH_TOKEN=your-refresh-token
GMAIL_USER_EMAIL=your-email@gmail.com
POLL_INTERVAL=30s

# 필터 설정 (콤마 구분)
FILTER_FROM=jira@atlassian.com,github@github.com
FILTER_LABEL=INBOX

# ClickUp 설정
CLICKUP_API_TOKEN=pk_your_token
CLICKUP_LIST_ID=your-list-id
HISTORY_MAX_SIZE=100
